(defun solve (n l)
  (if (zerop n)
      (cons (length l) l)
      (let ((d (cond ((<= 8 n) 8)
                     ((<= 4 n) 4)
                     ((<= 2 n) 2)
                     (t 1))))
        (solve (- n d) (cons d l)))))

(defun main ()
  (format t "~{~a~%~}" (solve (read) ())))
(main)
